### PR TITLE
Refactor server

### PR DESCRIPTION
**Pull request by fpellet**
Create solution for project
Default target of fake is Build
Update Fake script to build and run solution
Extract static file of static.fsx

### CODE REVIEW

**Comment by devcrafting** [comment]
LGTM

**Comment by Ouarzy** [comment]
Don't work on linux :/

These lines are required in **build.local.fsx**:
_#r "packages/FSharp.Compiler.Service/lib/net45/FSharp.Compiler.Service.dll"
#I "packages/FAKE/tools"_

The compiler dll is required to load FakeLib (MSBuildHelper is from Fake).

And Mono is only compatible with .NET 4.5, need to downgrade^^

**Comment by Ouarzy** [comment]
As I'm the only Linux Hipster so far,

I accept the PR and count on you to fix this in the next PR ;)

**Comment by fpellet** [comment]
It's works on linux, but you must use last version of mono (4.4)
But there are bug on watch. The script stop immediately.
And restore.and.build.sh target to run and not build

**Pull request merged**
